config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :users

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters

  def to_s
    "#{pseudo}"
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:pseudo, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:pseudo, :email, :password, :current_password)}

  end


end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:prenom, :nom, :surnom, :avatar, :hero, :age, :sexe, :monde, :race, :origine, :classe, :pv, :pm, :destin, :histoire, :competences, :inventaire, :published_at, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @user = current_user
    @user = User.find(params[:id])
    @users = User.all
    @user.destroy

  end

  def new
    @user = User.new
  end

  def show

  end

  def edit
  end

  def create
    @user = User.new(params[:id])

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to new_user_profile_path(:user_id => @user)
    else
      render :action => 'new'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= simple_form_for(@character) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form_chara">
    <h3>Informations générales</h3>
    <div class="form_general">
      <div class="form_left">
        <%= f.input :prenom %>
        <%= f.input :nom %>
        <%= f.input :surnom %>
        <%= f.input :age %>
        <%= f.input :sexe, collection: [['0', 'Féminin'], ['1', 'Masculin']], label_method: :second, value_method: :first %>
      </div>
      <div class="form_mid">
        <%= f.input :race %>
        <%= f.input :classe, label: 'Classe / Occupation' %>
        <%= f.input :monde %>
        <%= f.input :origine %>
      </div>
      <div class="form_right">
        <%= f.input :pv %>
        <%= f.input :pm %>
        <%= f.input :destin, label: 'Niveau' %>
        <%= f.input :avatar %>
        <%= f.input :hero, label: 'Image bannière' %>
      </div>
    </div>
    <h3>Précisions</h3>
    <%= f.input :histoire %>
    <div class="form_more">
      <%= f.input :competences %>
      <%= f.input :inventaire %>
    </div>
    <%= f.association :user %>
  </div>

  <div class="form_submit">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'bannière du site' %>
  </div>
  <div class="header_profile header_btn">
    <h1>Editer une fiche</h1>
    <h2>Changer les informations</h2>
    <%= link_to 'Retour à la liste des personnages', characters_path %>
  </div>
</header>

<div id="main">
  <%= render 'form', character: @character %>
  <div class="edit_links">
    <%= link_to 'Show', @character %>
    <%= link_to 'Back', characters_path %>
  </div>
</div>

app/views/characters/index.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'bannière du site' %>
  </div>
  <div class="header_profile header_btn">
    <h1>Liste des personnages</h1>
    <%= link_to 'New Character', new_character_path %>

  </div>
</header>

<div id="main" class="chara_list">

  <% if @characters.any? %>

    <% @characters.sort_by(&:prenom).each do |character| %>
      <div class="character">
        <div class="chara_avatar" style="background-image: url('<%= character.avatar %>')"></div>
        <div class="chara_infos">
          <%= link_to character.prenom, character %>
          Originaire de <%= character.monde %>
        </div>
        <% if current_user == character.user %>
          <div class="chara_actions">
            <%= link_to 'Editer', edit_character_path(character) %>
            <%= link_to 'Supprimer', character, method: :delete, data: { confirm: 'Es-tu sûr.e de vouloir supprimer cette fiche ?' } %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% else %>
      <div class="notice">
        <p>Il n'y a aucun personnage créé pour le moment !</p>
        <%= link_to 'Inscrit-toi pour créer des fiches', new_user_registration_path %>
      </div>
  <% end %>
</div>

app/views/characters/new.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'bannière du site' %>
  </div>
  <div class="header_profile header_btn">
    <h1>Nouvelle fiche</h1>
    <h2>Ajouter un personnage</h2>
    <%= link_to 'Retour à la liste des personnages', characters_path %>
  </div>
</header>

<div id="main">

  <%= render 'form', character: @character %>

</div>

app/views/characters/show.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'bannière du site' %>
  </div>
  <div class="header_profile header_chara">
    <h1>
      <%= @character.prenom %> <%= @character.nom %>
      <span><%= @character.prenom %> <%= @character.nom %></span>
    </h1>
    <div>
      <h2>Créé.e par <%= link_to  @character.user.pseudo,  @character.user, class: "btn_user" %></h2>
      <% if current_user == @character.user %>
        <%= link_to 'Editer', edit_character_path(@character), class: "btn_edit" %>
      <% end %>
    </div>
  </div>
</header>

<div id="main">

  <div class="character_view">
    <div class="chara_head">
      <div class="chara_infos">
        <span><b>Surnom :</b> <%= @character.surnom %></span>
        <span><b>Âge :</b> <%= @character.age %></span>
        <span><b>Sexe :</b> <%= @character.sexe %></span>
        <span><b>Race :</b> <%= @character.race %></span>
        <span><b>Monde :</b> <%= @character.monde %></span>
        <span><b>Origine :</b> <%= @character.origine %></span>
        <span><b>Classe / métier :</b> <%= @character.classe %></span>

        <div class="chara_stats">

          <div class="stat pv">
            <b>PV</b>
            <div class="stat_bar">
              <div class="stat_bar_fill" style="width: <%= @character.pv %>%;"></div>
            </div>
          </div>
          <div class="stat pm">
          <b>PM/Autre</b>
            <div class="stat_bar">
              <div class="stat_bar_fill" style="width: <%= @character.pm %>%;"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="chara_avatar">
        <img src="<%= @character.avatar %>">
        <div class="level" title="Niveau"><span><%= @character.destin %></span></div>
      </div>
    </div>

    <div class="chara_about">

      <div class="chara_histoire">
        <h3>Histoire</h3>
        <div class="histoire_cont"><%= @character.histoire %></div>
      </div>
      <div class="chara_compet">
      <h3>Compétences</h3>
        <div class="compet_cont">
          <%= @character.competences %>
        </div>
      </div>
    </div>
    <div class="chara_bottom">
      <div class="chara_invent">
        <div class="invent_cont">
          <%= @character.inventaire %>
        </div>
      </div>
      <div class="chara_bann" style="background-image: url('<%= @character.hero %>');"></div>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<header>
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'logo dé de jeu de rôle' %>
  </div>
  <div class="header_title">
    <%= image_tag 'dice.svg', alt: 'bannière du site' %>
    <h1>
      <b>Roll your</b>
      <span>chara</span>
    </h1>
  </div>
  <div class="header_desc">
    <h2>L'artefact mystique qui facillite vos scéances de jeu de rôle</h2>
    <p>Envie de sauvegarder tes fiches personnage au même endroit pour t'y retrouver sans avoir à ouvrir tes docs word ? De sauvegarder en direct ta progression dans ton épopée ? En quelques clics, le tour est joué avec Roll Your Chara !</p>
  </div>
</header>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roll your characters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <div id="navigation_bar">
    <a class="logo_site" href="/"><%= image_tag 'logo_flat.svg', alt: 'logo dé de jeu de rôle' %></a>
    <div class="nav_links">
      <%= link_to 'Membres', users_path, class: 'member_list' %>
      <%= link_to 'Personnages', characters_path, class: 'chara_list' %>
      <% if current_user %>
        <%= link_to 'Créer une fiche', new_character_path, class: 'new_fiche' %>
        <div class="links_connected">
          <%= link_to current_user.pseudo, current_user, class: 'profile' %>
          <%= link_to 'éditer ton profil', edit_user_registration_path, class: 'edit_profile' %>
          <%= button_to "logout", destroy_user_session_path, method: :delete, class: 'logout_btn'  %>
        </div>
        <% else %>
        <div class="links_notconnected">
          <%= button_to new_user_session_path, class: 'login-button' do %>se connecter<% end %>
          <%= link_to 'Inscription', new_user_registration_path, class: 'sign_btn' %>
        </div>
      <% end %>
    </div>
  </div>

  <body>
    <%= yield %>
  </body>
  <script src="//pull.cappuccicons.com/cpf.js"></script>
</html>

app/views/user/show.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_1.svg', alt: 'bannière du site' %>
  </div>
  <div class="header_profile">
    <h1>Tes fiches personnage</h1>
    <h2>@Pseudo</h2>
  </div>
</header>

<div id="main"></div>

app/views/users/index.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'bannière du site' %>
  </div>
  <div class="header_profile">
    <h1>Liste des membres</h1>
  </div>
</header>

<div id="main" class="member_list">
  <% @users.sort_by(&:pseudo).each do |user| %>
    <div class="member">
      <%= link_to user.pseudo, user %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<header class="header_perso">
  <div class="header_illustration">
    <%= image_tag 'fond_png.png', alt: 'bannière du site' %>
  </div>
  <div class="header_profile">
    <h1>Fiches personnage</h1>
    <h2>@<%= @user.pseudo %></h2>
  </div>
</header>

<div id="main" class="chara_list">
    <% if @user.characters.any? %>
      <% @user.characters.sort_by(&:prenom).each do |character| %>
        <div class="character">
          <div class="chara_avatar" style="background-image: url('<%= character.avatar %>')"></div>
          <div class="chara_infos">
            <%= link_to character.prenom, character %>
            Originaire de <%= character.monde %>
          </div>
          <div class="chara_actions">
            <% if current_user == @user %>
              <%= link_to 'Editer', edit_character_path(character) %>
              <%= link_to 'Supprimer', character, method: :delete, data: { confirm: 'Es-tu sûr.e de vouloir supprimer cette fiche ?' } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>

    <% if current_user == @user %>
      <div class="notice">
        <p>Tu n'as pas encore créé de fiche... 😥</p>
        <%= link_to 'Créé ta première fiche', new_character_path %>
      </div>
      <%else%>
        <div class="notice">
          <p><%= @user.pseudo %> n'a pas encore créé de fiche !
        </div>
    <% end %>

  <% end %>
</div>